lab50:
  window:   
    - editor
    - readme
    - terminal

  files: 
    - !exclude "*"
    - !exclude "__init__.py"
    - !include lab1_1.py

check50: 
  files: &check50_files
    - !exclude "*"
    - !require lab1_1.py

submit50: 
  files: *check50_files
  style: true