lab50:
  window:   
    - editor
    - readme
    - terminal

  files: 
    - !exclude "*"
    - !exclude "__init__.py"
    - !include lab7_1.py
    - !include cereal.csv
   

check50: 
  files: &check50_files
    - !exclude "*"
    - !require lab7_1.py
    

submit50: 
  files: *check50_files
  style: true