lab50:
  window:   
    - editor
    - readme
    - terminal

  files: 
    - !exclude "*"
    - !exclude "__init__.py"
    - !include lab7_1.py
    - !include 2021-07-08_clean-hashtags.tsv 

check50: 
  files: &check50_files
    - !exclude "*"
    - !require lab7_1.py
    - !require 2021-07-08_clean-hashtags.tsv

submit50: 
  files: *check50_files
  style: true