lab50:
  window:   
    - editor
    - readme
    - terminal

  files: 
    - !exclude "*"
    - !exclude "__init__.py"
    - !include assignment7.py
    - !include accounts.txt

check50: 
  files: &check50_files
    - !exclude "*"
    - !require assignment7.py
    - !require accounts.txt

submit50: 
  files: *check50_files
  style: true