lab50:
  window:   
    - editor
    - readme
    - terminal

files: 
   - !exclude "*"
   - !include problem1.py

check50: 
  files: &check50_files
    - !exclude "*"
    - !require problem1.py

submit50: 
  files: *check50_files
  style: true