lab50:
  window:   
    - editor
    - readme
    - terminal

  files: 
    - !exclude "*"
    - !exclude "__init__.py"
    - !include assignment3.py
    
check50: 
  files: &check50_files
    - !exclude "*"
    - !require assignment3.py

submit50: 
  files: *check50_files
  style: true