lab50:
  window:   
    - editor
    - readme
    - terminal

  files: 
    - !exclude "*"
    - !exclude "__init__.py"
    - !include assignment6.py
    - !include course1.txt
    - !include course2.txt

check50: 
  files: &check50_files
    - !exclude "*"
    - !require assignment6.py
    - !require course1.txt
    - !require course2.txt

submit50: 
  files: *check50_files
  style: true