lab50:
  window:   
    - editor
    - readme
    - terminal

  files: 
    - !exclude "*"
    - !exclude "__init__.py"
    - !include lab6_2.py
 
check50: 
  files: &check50_files
    - !exclude "*"
    - !require lab6_2.py

submit50: 
  files: *check50_files
  style: true