lab50:
  window:   
    - editor
    - readme
    - terminal

  files: 
    - !exclude "*"
    - !exclude "__init__.py"
    - !include lab4_1.py
    - !include datafile.txt

check50: 
  files: &check50_files
    - !exclude "*"
    - !require lab4_1.py
    - !require datafile.txt

submit50: 
  files: *check50_files
  style: true