lab50:
  window:   
    - editor
    - readme
    - terminal

  files: 
   - !exclude "*"
   - !include assignment1.py

check50: 
  files: &check50_files
    - !exclude "*"
    - !require assignment1.py

submit50: 
  files: *check50_files
  style: true