lab50:
  window:   
    - editor
    - readme
    - terminal

  files: 
    - !exclude "*"
    - !exclude "__init__.py"
    - !include lab5_1.py
    - !include article1.txt 

check50: 
  files: &check50_files
    - !exclude "*"
    - !require lab5_1.py
    - !require article1.txt

submit50: 
  files: *check50_files
  style: true